"""empty message

Revision ID: 1ab38b8a95dd
Revises: d4ace1df7faf
Create Date: 2021-03-17 17:12:36.749249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab38b8a95dd'
down_revision = 'd4ace1df7faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipients', sa.Column('filer_ein', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipients', 'filer_ein')
    # ### end Alembic commands ###
